[platformio]
default_envs = esp32-c3-supermini

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.partitions = huge_app.csv

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    fbiego/ESP32Time@^2.0.6
    h2zero/NimBLE-Arduino@^2.1.0
    adafruit/Adafruit GFX Library@^1.12.0
    adafruit/Adafruit SSD1306@^2.5.11
    https://github.com/fbiego/chronos-esp32.git
    
